title: Workspace App
remote_theme: just-the-docs/just-the-docs

mermaid:
  version: "9.1.3"

just_the_docs:
  callouts:
    tip:
      title: ğŸ¤ Tip
      color: purple
    info:
      title: â„¹ï¸ Info
      color: blue
    attention:
      title: â• Attention
      color: yellow
    download:
      title: ğŸ’¾ Download
      color: grey-dk
